projects:
  app:
    # generated schema is set as main! (so codegen can generate correct types)
    schemaPath: src/generated/app.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
      override:
        - schema: src/schema/schema.graphql
          overrides: src/schema/overrides.graphql
          output: src/generated/app.graphql
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/generated/prisma.ts
